[tools]
rust = "1.88.0"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:git-delta" = "latest"
"cargo:rage" = "latest" # provides `rage` and `age` binaries
"cargo:ripgrep" = "latest" # provides `rg`
"cargo:fd-find" = "latest" 
"cargo:ncspot" = "latest"
"cargo:viu" = "latest"

node = "22.14.0"
"npm:commitizen" = "latest"
"npm:turbo" = "latest"

terraform = "1.11.4"
zig = "0.14.1"
pnpm = "10.13.1"

[settings]
experimental = true
verbose = false
legacy_version_file = true
idiomatic_version_file_enable_tools = ["node"]
jobs = 6
not_found_auto_install = true
asdf_compat = true
