[tools]
# Essential development tools
node = "22.14.0"
python = "3.13.5"

# Package managers
pnpm = "10.13.1"
npm = "latest"

[settings]
experimental = true
verbose = false
legacy_version_file = true
idiomatic_version_file_enable_tools = ["node"]
jobs = 6
not_found_auto_install = true
asdf_compat = true
